// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hukokucskkfotrgjyufs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1a29rdWNza2tmb3RyZ2p5dWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTA1NDUsImV4cCI6MjA1OTU4NjU0NX0.FoGXRFku2TenONuM_a943A_04irsZs_J9tD0v8h9y1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);